services:
  audiohardshelf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audiohardshelf
    restart: unless-stopped

    volumes:
      - logs-data:/app/logs:Z

    environment:
      - ABS_URL=${ABS_URL}
      - ABS_USER_ID=${ABS_USER_ID}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-0 */1 * * *}
      - ABS_API_KEY=${ABS_API_KEY}
      - HARDCOVER_API_KEY=${HARDCOVER_API_KEY}

volumes:
  logs-data:
