services:
  audiohardshell:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audiohardshell
    restart: unless-stopped

    volumes:
      - logs-data:/app/logs:Z

    environment:
      - ABS_URL=${ABS_URL}
      - ABS_USER_ID=${ABS_USER_ID}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-0 */1 * * *}

    secrets:
      - source: abs_api_key
        target: /run/secrets/abs_api_key
      - source: hardcover_api_key
        target: /run/secrets/hardcover_api_key

secrets:
  abs_api_key:
    file: ./secrets/abs_api_key.txt
  hardcover_api_key:
    file: ./secrets/hardcover_api_key.txt

volumes:
  logs-data:
